---
- hosts: ServidoresMySQL57
  tasks:

    - name: setear hostname
      hostname: name={{ansible_hostname}}

    - name: instalar epel
      yum:
        name:
          - epel-release

    - name: instalar MySQL57 repo
      yum: name=http://dev.mysql.com/get/mysql80-community-release-el7-6.noarch.rpm

    - name: disable mysql 8 repo
      ini_file:
        dest: /etc/yum.repos.d/mysql-community.repo
        section: mysql80-community
        option: enabled
        value: "0"
    
    - name: enable mysql 57 repo
      ini_file:
        dest: /etc/yum.repos.d/mysql-community.repo
        section: mysql57-community
        option: enabled
        value: "1"

    - name: disable clave mysql57
      ini_file:
        dest: /etc/yum.repos.d/mysql-community.repo
        section: mysql57-community
        option: gpgcheck
        value: "0"

    - name: instalar MySQL57 server
      yum:
        name: "{{ packages }}"
        state: present

      vars:
        packages:
          - mysql-community-server
          - mysql-community-client
          - MySQL-python

    - name: iniciar servicio MySQL
      service: name=mysqld state=started enabled=true
